### ISSUE TITLE
SQL-Error  wenn ein neues Frontend-Modul angelegt wird

### ISSUE THREAD

**Issue by srhinow** [mindbird/contao-referenzen#1]
Ich bekomme ein SQL-Error wenn ich ein neues Frontend-Modul anlegen möchte da der SQL-Field-Type ein integer ist und der Default-Wert nen leerer String. 
Die Datei dca/tl_module.php sollte so aussehen damit es funktioniert:
Also statt  'default' => '', muss da  'default' => 0, stehen.
```
$GLOBALS ['TL_DCA'] ['tl_module'] ['fields'] ['reference_archiv'] = array(
    'label' => &$GLOBALS ['TL_LANG'] ['tl_module'] ['reference_archiv'],
    'default' => 0,
    'inputType' => 'select',
    'foreignKey' => 'tl_reference_archive.title',
    'eval' => array(
        'mandatory' => true,
        'tl_class' => 'w50',
        'submitOnChange' => true
    ),
    'sql' => "int(10) unsigned NOT NULL default '0'"
);
```
oder einfach die Zeile mit dem default weg lassen.

**Comment by Wusch** [comment]
Ich habe das Modul für Contao 4 überarbeitet. Es nutzt jetzt auch isotope direkt zum filtern der Einträge. Der aktuelle Master Branch kann gerne getestet werden.

**Comment by srhinow** [comment]
In meinem Fork bin ich dabei diverse Dinge umzustricken und hinzuzufügen. z.B. Filterung zur referenzierten Kategorie-Page (so kann man zu jeder Kategorie ne Page zuweisen und kann so statische Seiten anlegen wo dann das Modul immer die dazu passende Kategorie filtert), feutured-Flag per Referenz wie beim News-modul, Ausgabe der Filterung als Array und nicht per String im Frontend-Modul etc. <- habs aber noch nicht online gestellt.

Auch das mit der referenceId per GET wollte ich auch so ändern das es wie bei anderen Modulen per alias in der Url steht und dann per findByIdOrAlias suchen lassen.

**Comment by Wusch** [comment]
Dann schau dir mal den aktuellen Master Branch an. Habe die Serverseitige Filterung entfernt. Der Filter hat jetzt auch ein eigenes Template und bekommt ein Array der Kategorien wie in deinem Pull Request.

**Comment by srhinow** [comment]
Könntest du bitte die letzten Änderungen nen neuen Tag zuweisen? Da die Änderungen sonst im Master-Branch nicht von Packagist.org wahrgenommen werden und  er installiert immer nur den letzten Stand aus 1.0.5.
