### ISSUE TITLE
getSearchablePages-Hook verursacht Error

### ISSUE THREAD

**Issue by srhinow** [mindbird/contao-referenzen#4]
Hallo,
wenn ich bei der Systemwartung den Suchcache neu aufbauen will erscheint ein Fehler
# FatalThrowableError 
`Type error: Argument 3 passed to Contao\Model::findBy() must be of the type array, integer given, called in /var/www/p/paul-sohn.de/contao4/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php on line 975

Model::findBy('pids', array('1', '1'), 0, array('order' => 'id ASC')) in vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php (line 975)

Model::__callStatic('findByPids', array('pids', array('1', '1'), 0, array('order' => 'id ASC'))) in vendor/mindbird/contao-referenzen/src/ReferenceBackend.php (line 60) 
`
Hab aber aktuell auch keine schnelle Lsung dafür daher werde ich erstmal  den Hook Aufruf deaktivieren bis es dafür einen Fix gibt.

**Comment by Wusch** [comment]
Ich denke ich habe den Fehler behoben. Könntest du die aktuelle Version aus dem Masterbranch testen?

**Comment by srhinow** [comment]
Da ich ja, wie in dem anderen Issue von mir zu lesen ist, einen Fork gemacht habe und dann dort einiges erweitert habe, kann ich es nicht einfach an meinem Projekt ausprobieren und für einen Merge fehlt mir aktuell die Zeit.

Ich habe es versucht manuell anzupassen. Zum einen findet er jetzt die Klasse Reference nicht obwohl ich diese dort zu liegen habe und auch den gesamten Code mit dem hier von github dort rein kopiert. Auch den Cache und die Autoloader habe ich schon diverse Male durchlaufen lassen. 
```
Was ist das Problem?
Attempted to load class "Reference" from namespace "Mindbird\Contao\Reference\Models". Did you forget a "use" statement for e.g. "Symfony\Component\DependencyInjection\Reference" or "Symfony\Component\Validator\Tests\Fixtures\Reference"?
```

Auch wenn das soweit klappen sollte, bezweifle ich das es dann den Fehler nicht mehr gibt, denn es gibt in dem Model "Mindbird\Contao\Reference\Models\Reference" keine Methode findByPids noch in der vererbten Klasse "Model". Wenn es keine Methode gibt dann baut Contao sich das findBy und Pids auseinander und versucht dann dies Anhand eines in der tabelle befindlichen Feldes. In der tl_reference gibt es aber auch kein Feld Pids sondern nur pid.

**Comment by Wusch** [comment]
Fehler behoben. Läuft bei mir soweit auf der Testumgebung.
